shop_alma/apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name= 'register'),
    path('verify/', views.VerifyRegisterCodeView.as_view(), name= 'verify'),
    path('login/', views.LoginUserView.as_view(), name= 'login'),
    path('logout/', views.LogoutUserView.as_view(), name= 'logout'),
    path('remember_password/', views.RememberPasswordView.as_view(), name= 'remember_password'),
    path('change_password/', views.ChengPasswordView.as_view(), name= 'change_password'),
    
    path('userpanel/', views.UserPanelView.as_view(), name= 'userpanel'),
    path('show_last_orders/',views.show_last_orders,name='show_last_orders'),
    path('update_profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('show_user_payment/',views.show_user_payments,name='show_user_payment'),
    
]

shop_alma/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls", namespace= "main")),
    path('accounts/', include("apps.accounts.urls", namespace= "accounts")),
    path('products/', include("apps.products.urls", namespace= "products")),
    path('orders/', include("apps.orders.urls", namespace= "orders")),
    path('discounts/', include('apps.discounts.urls', namespace= "discounts")),
    path('payments/',include('apps.payment.urls',namespace='payments')),
    path('warehouses/', include("apps.warehouses.urls", namespace= "warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace='csf')),
    path("search/",include("apps.search.urls",namespace='search')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='apps.main.views.handler404'

shop_alma/templates/accounts_app/change_password.html
{% extends 'user_panel_template.html' %}
{% load render_partial %}
{% block title %}
پنل کاربری
{% endblock title %}

{% block content %}

<div class="limiter">
        <div class="dashboard">
            {% if user.is_authenticated %}

<div class="site__body">
        <div class="block">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6 d-flex mt-4 mt-md-0">
                        <div class="card flex-grow-1 mb-0">
                            <div class="card-body">
                                <h3 class="card-title">تغییر رمز عبور</h3>
                                                                        
                                <form action="" method="post">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-primary mt-4">ثبت تغییرات</button>
                                        
                                </form>                           
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 
<div id="dropDownSelect1"></div>

{% endif %}
        </div>
</div>
{% endblock content %}

shop_alma/templates/accounts_app/login.html
{% extends 'main_template.html' %}


{% block title %}
	کامپیوتر آلما
{% endblock title %}
    

{% block content %}

{% include "partials/banner/banner_box.html" with type=2 %}
<div class="limiter">
	<div class="container-login100" style="background-image: url('{{media_url}}/images/login/bg-01.jpg');">
		<div>
			<h2 class="header-text1-color">خوش آمدید</h2>
		</div>
		<div>
			<h5 class="header-text1-color">برای ورود نام کاربری و کلمه عبور خود را وارد کنید</h5>
		</div>
		<br>
		{% include "partials/message.html" %}
		<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
			<form action="" method="post">
				{% csrf_token %}
				<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
					<span class="label-input100">نام کاربری</span>
					{{ form.mobile_number }}
					<span class="focus-input100" data-symbol="&#xf206;"></span>
				</div>

				
				<div class="wrap-input100 validate-input" data-validate="Password is required">
					<span class="label-input100">کلمه عبور</span>
					{{ form.password}}
					<span class="focus-input100" data-symbol="&#xf190;"></span>
				</div>
				
				<div class="text-right p-t-8 p-b-31">
					<a href="{% url 'accounts:remember_password' %}">
						Forgot password?
					</a>
				</div>
				
				<div class="container-login100-form-btn">
					<div class="wrap-login100-form-btn">
						<div class="login100-form-bgbtn"></div>
						<button class="login100-form-btn">
							ورود
						</button>
					</div>
				</div>

				<div class="txt1 text-center p-t-25 p-b-20">
					<span>
						ورود به وسیله
					</span>
				</div>

				<div class="flex-c-m">
					<a href="#" class="login100-social-item bg1">
						<i class="fab fa-facebook-f"></i>
					</a>

					<a href="#" class="login100-social-item bg4">
						<i class='fab fa-instagram'></i>
					</a>

					<a href="#" class="login100-social-item bg3">
						<i class="fab fa-google"></i>
					</a>
				</div>

				<div class="flex-col-c p-t-25">
					<span class="txt1 p-b-17">
						ایجاد کاربری جدید
					</span>

					<div class="wrap-login100 p-l-55 p-r-55 p-t-25 p-b-25">
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<div class="container-login100-form-btn">
								<div class="wrap-login100-form-btn">
									<div class="login100-form-bgbtn"></div>
									<button type="submit" class="login100-form-btn">
										<a class="login100-form-btn" href="{% url 'accounts:register' %}">ثبت نام</a>
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

shop_alma/templates/accounts_app/register.html
{% extends 'main_template.html' %}


{% block title %}
    بازرگانی مهوار ابرشهر
{% endblock title %}
    

{% block content %}
{% include "partials/banner/banner_box.html" with type=2 %}
<div class="limiter">
	<div class="container-login100" style="background-image: url('{{media_url}}/images/login/bg-01.jpg');">
		<div>
			<h2 class="header-text1-color">خوش آمدید</h2>
		</div>
		<div>
			<h5 class="header-text1-color">برای ثبت نام لطفا کد کاربری و کلمه عبور خود را انتخاب و ارسال کنید</h5>
		</div>
		<br>
		{% include "partials/message.html" %}
		<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
			<form action="" method="post">
				{% csrf_token %}
                
                <div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
					<span class="label-input100"> شماره موبایل </span>
					{{ form.mobile_number }}
					<span class="focus-input100" data-symbol="&#xf206;"></span>
				</div>
				
                <div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
					<span class="label-input100">کلمه عبور </span>
					{{ form.password1}}
					<span class="focus-input100" data-symbol="&#xf190;"></span>
				</div>

				<div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
					<span class="label-input100"> تکرار کلمه عبور </span>
					{{ form.password2}}
					<span class="focus-input100" data-symbol="&#xf190;"></span>
				</div>
                <div class="container-login100-form-btn">
					<div class="wrap-login100-form-btn">
						<div class="login100-form-bgbtn"></div>
						
							<input type="submit" value=" ثبت نام  " class="login100-form-btn input-reg">      
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock content %}

shop_alma/templates/accounts_app/remember_password.html
{% extends 'main_template.html' %}

{% block content %}

{% include "partials/banner/banner_box.html" with type=2 %}

    <!-- site__body -->
    
    <div class="site__body">
        <div class="block">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <div class="card flex-grow-1 mb-md-0">
                            <div class="card-body">

                            
                        <form action="" method="post">
                            {% csrf_token %} 
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
                        </form>



                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

<div id="dropDownSelect1"></div>

{% endblock content %}

shop_alma/templates/accounts_app/show_user_payment.html
{% extends "user_panel_template.html" %}
{% load render_partial %}
{% load humanize %}
{% block title %}
ویرایش پروفایل
{% endblock title %}

{% block content %}
{% if payments %}
    <div class="dashboard__orders card">
        <div class="card-header">
            <h5>لیست پرداخت‌های شما</h5>
            <div class="card-divider"></div>
            <div class="card-table">
                <div class="table-responsive-sm">
                    <table>
                        <thead>
                            <tr>
                                <th>شماره پرداخت</th>
                                <th>تاریخ</th>
                                <th>وضعیت</th>
                                <th>مبلغ پرداخت</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for payment in payments %}
                                <tr>
                                    <td><a href="">{{ payment.id }}</a></td>
                                    <td>{{ payment.register_date }}</td>
                                    <td>
                                        {% if payment.is_finally %}
                                            <span class="text-success">پرداخت شد</span>
                                        {% else %}
                                            <span class="text-danger">پرداخت نشده</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ payment.amount|intcomma }}</td> <!-- اگر مبلغی وجود دارد -->
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="alert alert-danger" role="alert">
        هیچ پرداختی یافت نشد.
    </div>
{% endif %}

{% endblock content %}

shop_alma/templates/accounts_app/update_profile.html
{% extends "user_panel_template.html" %}
{% load render_partial %}
{% block title %}
ویرایش پروفایل
{% endblock title %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-9">
                <div class="card flex-grow-1 mb-md-0">
                    <div class="card-body">
                        <h3 class="card-title">ویرایش پروفایل</h3>
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_table }}
                            <img src="{{ media_url }}{{ image_url }}" style="width: 100px; height: 100px;" alt="ax">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary mt-4">ویرایش</button>
                                <a href="{% url 'accounts:userpanel' %}" class="btn btn-info mt-4"> انصراف</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

shop_alma/templates/accounts_app/userpanel.html
{% extends 'user_panel_template.html' %}
{% load render_partial %}
{% block title %}
پنل کاربری
{% endblock title %}

{% block content %}
{% comment %} {% include "partials/banner/banner_box.html" with type=4 %} {% endcomment %}
<div class="limiter">
        <div class="dashboard">
            {% include "accounts_app/partials/user_info.html" %}
            {% render_partial 'accounts:show_last_orders' %}
        </div>
</div>
{% endblock content %}
    

shop_alma/templates/accounts_app/verify_register.html
{% extends 'main_template.html' %}


{% block title %}
    بازرگانی مهوار ابرشهر
{% endblock title %}
    

{% block content %}
{% include "partials/banner/banner_box.html" with type=2 %}
<div class="limiter">
	<div class="container-login100" style="background-image: url('{{media_url}}/images/login/bg-01.jpg');">
		<div>
			<h2 class="header-text1-color">خوش آمدید</h2>
		</div>
		<div>
			<h5 class="header-text1-color">برای ثبت نام کد دریافتی خود را وارد کنید</h5>
		</div>
		<br>
		{% include "partials/message.html" %}
		<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
			<form action="" method="post">
				{% csrf_token %}
                <label>کد دریافتی</label>
                {{ form.as_p }}
				<br><br>
                <div class="container-login100-form-btn">
					<div class="wrap-login100-form-btn">
						<div class="login100-form-bgbtn"></div>
						
							<button type="submit" class="login100-form-btn input-reg">ارسال کد</button>    
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock content %}

shop_alma/templates/accounts_app/verify_register_code.html
{% extends 'main_template.html' %}


{% block title %}
    بازرگانی مهوار ابرشهر
{% endblock title %}
    

{% block content %}

    <!-- site__body -->
    
    <div class="site__body">
        <div class="page-header">
            <div class="page-header__container container">
                <div class="page-header__breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">خانه</a>
                                /
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">حساب کاربری</a>
                                /
                            </li>
                            <li class="active" aria-current="page">احراز هویت</li>
                        </ol>
                    </nav>
                </div>
                <div class="page-header__title d-flex justify-content-center">
                    <h1>تایید شماره موبایل</h1>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <div class="card flex-grow-1 mb-md-0">
                            <div class="card-body">

                            
                        <form action="" method="post">
                            {% csrf_token %} 
                            <label>کد دریافتی</label>
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
                        </form>



                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
<br><br><br><br>
{% endblock content %}
    