shop_alma/apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name= 'register'),
    path('verify/', views.VerifyRegisterCodeView.as_view(), name= 'verify'),
    path('login/', views.LoginUserView.as_view(), name= 'login'),
    path('logout/', views.LogoutUserView.as_view(), name= 'logout'),
    path('remember_password/', views.RememberPasswordView.as_view(), name= 'remember_password'),
    path('change_password/', views.ChengPasswordView.as_view(), name= 'change_password'),
    
    path('userpanel/', views.UserPanelView.as_view(), name= 'userpanel'),
    path('show_last_orders/',views.show_last_orders,name='show_last_orders'),
    path('update_profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('show_user_payment/',views.show_user_payments,name='show_user_payment'),
    
]

shop_alma/apps/main/urls.py
from django.urls import path
from . import views

app_name="main"
urlpatterns = [
    path('', views.index, name='index'),
    path('sliders/',views.sliderView.as_view(),name='sliders'),
]

shop_alma/apps/orders/urls.py
from django.urls import path
from .import views

app_name='orders'
urlpatterns = [
    path('shop_cart/',views.ShopCartView.as_view(),name='shop_cart'),
    path('add_to_shop_cart/',views.add_to_shop_cart,name='add_to_shop_cart'),
    path('status_of_shop_cart/',views.status_of_shop_cart,name='status_of_shop_cart'),
    path('delete_from_shop_cart/',views.delete_from_shop_cart,name='delete_from_shop_cart'),
    path('update_shop_cart/',views.update_shop_cart,name='update_shop_cart'),
    path('show_shop_cart/',views.show_shop_cart,name='show_shop_cart'),
    path('create_order/',views.CreateOrderView.as_view(),name='create_order'),
    path('checkout_order/<int:order_id>/',views.CheakoutOrderView.as_view(),name='checkout_order'),
    path('applay_coupon/<int:order_id>/',views.ApplyCoupon.as_view(),name="applay_coupon"),

]

shop_alma/apps/products/urls.py
from django.urls import path
from . import views

app_name='products'
urlpatterns = [
    path('cheapest_products/', views.get_cheapest_products, name="cheapest_products"),
    path('last_products/', views.get_last_products, name="last_products"),
    path('popular_product_group/', views.get_popular_product_group, name="popular_product_group"),
    path('product_details/<slug:slug>/', views.ProductDetailView.as_view(), name="product_details"),
    path('related_product/<slug:slug>/', views.get_related_products, name="related_product"),
    path('product_groups/', views.ProductGroupView.as_view(), name="product_groups"),
    path('products_of_group/<slug:slug>/', views.ProductsByGroupView.as_view(), name="products_of_group"),
    path('ajax_admin/', views.get_filter_value_for_feature, name="filter_value_for_feature"),
    path('product_groups_partial/', views.get_product_groups, name="product_groups_partial"),
    path('brands_partial<slug:slug>/', views.get_brands, name="brands_partial"),
    path('features_for_filter<slug:slug>/', views.get_feautres_for_filter, name="features_for_filter"),
    path('shop/', views.ProductAllView.as_view(), name="shop"),
    path("status_of_compare_list/", views.status_of_compare_list, name="status_of_compare_list"),
    path("compare_table/",views.compare_table,name="compare_table"),
    path("add_to_compare_list/", views.add_to_compare_list, name="add_to_compare_list"),
    path("delete_from_compare_list/", views.delete_from_compare_list, name="delete_from_compare_list"),

]

shop_alma/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls", namespace= "main")),
    path('accounts/', include("apps.accounts.urls", namespace= "accounts")),
    path('products/', include("apps.products.urls", namespace= "products")),
    path('orders/', include("apps.orders.urls", namespace= "orders")),
    path('discounts/', include('apps.discounts.urls', namespace= "discounts")),
    path('payments/',include('apps.payment.urls',namespace='payments')),
    path('warehouses/', include("apps.warehouses.urls", namespace= "warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace='csf')),
    path("search/",include("apps.search.urls",namespace='search')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='apps.main.views.handler404'

shop_alma/templates/partials/footer.html
  <footer>
    <div class="container">
      <div class="col-lg-12">
        <p>Copyright © 2048 LUGX Gaming Company. All rights reserved. &nbsp;&nbsp; <a rel="nofollow" href="https://templatemo.com" target="_blank">Design: TemplateMo</a></p>
      </div>
    </div>  
  </footer>

shop_alma/templates/partials/header.html
  {% load static %}
  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->

                    <!-- ***** Menu Start ***** -->
                    <a class='menu-trigger'>
                      {% include "partials/navbar.html/" %}
                    </a>
                    <!-- ***** Menu End ***** -->
  </header -->

  <!-- ***** Header Area End ***** -->

shop_alma/templates/partials/message.html
        <div class="">
            {% if messages %}
            {% for message in messages %}
                    <h5 class="alert alert-{{message.tags}}">
                        {{message}}
                    </h5>
                {% endfor %}
            {% endif %}

        </div>

shop_alma/templates/partials/navbar.html
<nav>
  <div class="wrapper">
    <ul class="nav-links">
      <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
      <li><a href='{% url "main:index" %}'> صفحه اصلی </a></li>
      <li><a href='{% url "products:shop" %}'> فروشگاه </a></li>
      <li>
        <a href="#" class="desktop-item"> دسته بندی کالاها </a>
        <input type="checkbox" id="showMega">
        <label for="showMega" class="mobile-item"> دسته بندی کالاها </label>
        <div class="mega-box">
          <div class="content">
            <div class="row">
              <img
                src="https://fadzrinmadu.github.io/hosted-assets/responsive-mega-menu-and-dropdown-menu-using-only-html-and-css/img.jpg"
                alt="">
            </div>
            <div class="row">
              <header> طراحی سایت </header>
              <ul class="mega-links">
                <li><a href="#"> سایت فروشگاهی </a></li>
                <li><a href="#"> سئو </a></li>
                <li><a href="#"> پایتون </a></li>
              </ul>
            </div>
            <div class="row">
              <header> لپ تاپ </header>
              <ul class="mega-links">
                <li><a href="#"> لپ تاپ </a></li>
                <li><a href="#"> قطعات </a></li>
                <li><a href="#"> لوازم جانبی </a></li>
              </ul>
            </div>
            <div class="row">
              <header> تعمیرات </header>
              <ul class="mega-links">
                <li><a href="#"> مادربورد </a></li>
                <li><a href="#"> پاور </a></li>
                <li><a href="#"> گرافیک </a></li>
                <li><a href="#"> مانیتور </a></li>
              </ul>
            </div>
          </div>
        </div>
      </li>
      <li>
        <a href="#" class="desktop-item"> مقالات </a>
        <input type="checkbox" id="showDrop">
        <label for="showDrop" class="mobile-item"> مقالات </label>
        <ul class="drop-menu">
          <li><a href="#"> برنامه نویسی </a></li>
          <li><a href="#"> سخت افزار </a></li>
          <li><a href="#"> قطعات </a></li>
          <li><a href="#"> تعمیرات </a></li>
        </ul>
      </li>
      <li><a href="#"> درباره ما </a></li>
      <li><a href="#"> ارتباط با ما </a></li>

    </ul>

    <div class="wrapper">
      <ul class="nav-links">
        <li class="main-button a">
          <a class="desktop-item" href=""> حساب کاربری</a>
          <input type="checkbox" id="showDrop">
          <label for="showDrop" class="mobile-item"> حساب کاربری</label>
          <ul class="drop-menu">
            {% if user.is_authenticated %}
            <li><a href='{% url "accounts:userpanel" %}'> پنل کاربری </a></li>
            <li><a href='{% url "accounts:logout" %}'> خروج </a></li>
            {% else %}

            <li><a href="{% url 'accounts:login' %}">ورود</a></li>
            <li><a href="{% url 'accounts:register' %}">ثبت نام</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      <!--***** Logo Start ***** -->
      <a href="index.html" class="logo">
        <img src="{{media_url}}/images/logo.png" alt="" style="width: 158px ">
      </a>
      <!-- ***** Logo End ***** -->

      <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
    </div>
    <div style="display:flex; flex_direction:row;">
      <div class="indicator">
        <a href='{% url "orders:shop_cart" %}'>
          <span>
            <i class="fa fa-shopping-basket basket" aria-hidden="true"></i>
          </span>
          <span class="indicator__value" id="indicator__value">0</span>
        </a>
      </div>
      
      <div  id="compare_count_icon" class="indicator">
        <a href='{% url "products:compare_table" %}'>
          <span>
            <i class="fa fa-play basket" aria-hidden="true"></i>
          </span>
          <span class="indicator__value" id="compare_count">0</span>
        </a>
        
      </div>
      
      {% if user.is_authenticated %}
      <div class="indicator">
          <span>
                <a href="{% url 'accounts:userpanel' %}" class="topbar-link"> <i class="fa fa-user user-panel"></i></a>
          </span>
      </div>
      {% endif %}


    </div>

</nav>

shop_alma/templates/partials/user_panel_header.html
<div class="site-header__topbar topbar">
    <div class="topbar__container container">
        <div class="topbar__row">
            <div class="topbar__item topbar__item--link"><a class="topbar-link" href="about-us.html">درباره ما</a></div>
            <div class="topbar__item topbar__item--link"><a class="topbar-link" href="contact-us.html">تماس با ما</a>
            </div>
            <div class="topbar__spring"></div>
            <div class="topbar__item">
                <div class="topbar-dropdown">
                    {% if user.is_authenticated %}
                    <button class="topbar-dropdown__btn" type="button">
                        <a href="{% url 'accounts:userpanel' %}" class="topbar-link">پنل کاربری</a>
                        <i class="fa fa-user"></i>
                    </button>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>