shop_alma/apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name= 'register'),
    path('verify/', views.VerifyRegisterCodeView.as_view(), name= 'verify'),
    path('login/', views.LoginUserView.as_view(), name= 'login'),
    path('logout/', views.LogoutUserView.as_view(), name= 'logout'),
    path('remember_password/', views.RememberPasswordView.as_view(), name= 'remember_password'),
    path('change_password/', views.ChengPasswordView.as_view(), name= 'change_password'),
    
    path('userpanel/', views.UserPanelView.as_view(), name= 'userpanel'),
    path('show_last_orders/',views.show_last_orders,name='show_last_orders'),
    path('update_profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('show_user_payment/',views.show_user_payments,name='show_user_payment'),
    
]

shop_alma/apps/products/urls.py
from django.urls import path
from . import views

app_name='products'
urlpatterns = [
    path('cheapest_products/', views.get_cheapest_products, name="cheapest_products"),
    path('last_products/', views.get_last_products, name="last_products"),
    path('popular_product_group/', views.get_popular_product_group, name="popular_product_group"),
    path('product_details/<slug:slug>/', views.ProductDetailView.as_view(), name="product_details"),
    path('related_product/<slug:slug>/', views.get_related_products, name="related_product"),
    path('product_groups/', views.ProductGroupView.as_view(), name="product_groups"),
    path('products_of_group/<slug:slug>/', views.ProductsByGroupView.as_view(), name="products_of_group"),
    path('ajax_admin/', views.get_filter_value_for_feature, name="filter_value_for_feature"),
    path('product_groups_partial/', views.get_product_groups, name="product_groups_partial"),
    path('brands_partial<slug:slug>/', views.get_brands, name="brands_partial"),
    path('features_for_filter<slug:slug>/', views.get_feautres_for_filter, name="features_for_filter"),
    path('shop/', views.ProductAllView.as_view(), name="shop"),
    path("status_of_compare_list/", views.status_of_compare_list, name="status_of_compare_list"),
    path("compare_table/",views.compare_table,name="compare_table"),
    path("add_to_compare_list/", views.add_to_compare_list, name="add_to_compare_list"),
    path("delete_from_compare_list/", views.delete_from_compare_list, name="delete_from_compare_list"),

]

shop_alma/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls", namespace= "main")),
    path('accounts/', include("apps.accounts.urls", namespace= "accounts")),
    path('products/', include("apps.products.urls", namespace= "products")),
    path('orders/', include("apps.orders.urls", namespace= "orders")),
    path('discounts/', include('apps.discounts.urls', namespace= "discounts")),
    path('payments/',include('apps.payment.urls',namespace='payments')),
    path('warehouses/', include("apps.warehouses.urls", namespace= "warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace='csf')),
    path("search/",include("apps.search.urls",namespace='search')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='apps.main.views.handler404'

shop_alma/apps/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product,ProductGroup,FeatureValue,Brand
from django.db.models import Q,Count,Min,Max
from django.views import View
from django.http import JsonResponse
from django.http import HttpResponse
import django_filters
from .filters import ProductFilter 
from django.core.paginator import Paginator
from .compare import CompareProduct



def get_root_group():
    return ProductGroup.objects.filter(Q(is_active=True) & Q(group_parent= None))

#==========================ارزانترین محصولات=========================================
def get_cheapest_products(request, *args, **kwargs):
    products= Product.objects.filter(is_active= True).order_by('price')[:4]
    product_groups= get_root_group()
    context= {
        "products": products,
        "product_groups": product_groups
    }
    return render(request, "products_app/partials/cheapest_products.html", context)


#========================جدیدترین محصولات=======================================
def get_last_products(request, *args, **kwargs):
    products= Product.objects.filter(is_active= True).order_by('-published_date')[:4]
    product_groups= get_root_group()
    context= {
        "products": products,
        "product_groups": product_groups
    }
    return render(request, "products_app/partials/last_products.html", context)

#========================دسته های محبوب =======================================
def get_popular_product_group(request, *args, **kwargs):
    # product_groups= ProductGroup.objects.filter(Q(is_active=True)).annotate(count= Count('product_of_groups')).order_by('-count')[:6]
    product_groups= ProductGroup.objects.filter(Q(is_active=True))\
                    .annotate(count= Count('product_of_groups'))\
                    .order_by('-count')[:6]
                    
    context= {
        "product_groups": product_groups
    }
    return render(request, "products_app/partials/popular_product_group.html", context)

#========================جزئیات محصول =======================================
class ProductDetailView(View):
    def get(self, request, slug):
        product= get_object_or_404(Product, slug=slug)
        if product.is_active:
            return render(request, "products_app/product_detail.html", {'product':product})

#======================== محصولات مرتبط=======================================
def get_related_products(request, *args, **kwargs):
    curent_products= get_object_or_404(Product, slug=kwargs['slug'])
    related_products= []
    for group in curent_products.product_group.all() :
        related_products.extend(Product.objects.filter(Q(is_active=True) & (Q(product_group=group)) & ~Q(id= curent_products.id)))

    return render(request, "products_app/partials/related_products.html", {'related_products':related_products})

#======================== همه دسته ها =======================================
class ProductGroupView(View):   
    def get(self, request):
        product_groups= ProductGroup.objects.filter(Q(is_active=True))\
                        .annotate(count= Count('product_of_groups'))\
                        .order_by('-count')
        return render(request, "products_app/product_groups.html/", {'product_groups':product_groups})

#======================== لیت محصولات دسته ها =======================================
class ProductsByGroupView(View):
    def get(self,request, *args, **kwargs):        
        slug= kwargs['slug']
        current_group= get_object_or_404(ProductGroup, slug=kwargs['slug'])
        products= Product.objects.filter(Q(is_active=True) & Q(product_group=current_group))     
        res_aggre= products.aggregate(min=Min('price'), max=Max('price'),)
            
        #price filter
        filter= ProductFilter(request.GET,queryset=products)
        products= filter.qs
        
        #brand filter
        brand_filter= request.GET.getlist('brand')
        if brand_filter:
            products=products.filter(brand__id__in=brand_filter)
            
        #features filter
        feature_filter= request.GET.getlist('feature')
        if feature_filter:
            products=products.filter(product_feature__filter_value__id__in= feature_filter).distinct()
            
        sort_type= request.GET.get('sort_type')
        if not sort_type:
            sort_type="0"
        
        if sort_type=="1":
            products= products.order_by('price')
        
        elif sort_type=="2":
            products= products.order_by('-price')
        
        group_slug= slug
        product_per_page=10                                     # تعداد کالاها در هر صفحه  
        paginator= Paginator(products, product_per_page)        #
        page_number= request.GET.get('page')                    # بدست آوردن شماره صفحه جاری
        page_obj= paginator.get_page(page_number)               # لیست کالاها بعد از صفحه بندی برای نمایش در صفحه جاری
        product_count= products.count()                         # تعداد کل کالاهای موجود در این گروه 
        
        # لیست اعداد برای ساخت منو باز شونده برای تعیین تعداد کالای هر صفحه توسط کاربر
        show_count_product= []
        i= product_per_page
        while i<product_count:
            show_count_product.append(i)
            i*=2
        show_count_product.append(i)
        
        context={
            'products':products,
            'current_group': current_group,
            'res_aggre': res_aggre,
            'group_slug': group_slug,
            'page_obj': page_obj,
            'product_count': product_count,
            'show_count_product': show_count_product,
            'filter': filter,
            'sort_type': sort_type,
        }    
        
        return render(request, "products_app/products.html/", context)


#======================== جی کوئری ارتباط ویژگی ها =======================================
def get_filter_value_for_feature(request):
    if request.method == 'GET':
        feature_id= request.GET["feature_id"]
        feature_values= FeatureValue.objects.filter(feature_id= feature_id)
        res= {fv.value_title:fv.id for fv in feature_values}

        return JsonResponse(data=res, safe=False)

#========================= لیست گروه محصولات برای فیلتر =======================================
def get_product_groups(request):
    product_groups= ProductGroup.objects.annotate(count= Count('product_of_groups'))\
                    .filter(Q(is_active= True) & ~Q(count=0))\
                    .order_by('-count')
    return render(request, 'products_app/partials/product_groups.html', {'product_groups': product_groups})

#========================= لیست برند ها برای فیلتر =======================================
def get_brands(request, *args, **kwargs):
    product_group= get_object_or_404(ProductGroup, slug= kwargs['slug'])
    brand_list_id= product_group.product_of_groups.filter(is_active=True).values('brand_id')
    brands= Brand.objects.filter(pk__in= brand_list_id)\
                        .annotate(count= Count('brands'))\
                        .filter(~Q(count=0))\
                        .order_by('-count')
    return render(request, 'products_app/partials/brands.html', {'brands': brands})

#========================= لیست های دیگر فیلترها بر حسب مقادیر ویژگیهای کالاهای درون گروه =======================================
def get_feautres_for_filter(request, *args, **kwargs):
    product_group= get_object_or_404(ProductGroup, slug= kwargs['slug'])
    feature_list= product_group.feature_of_groups.all()
    feature_dict= dict()
    for feature in feature_list:
        feature_dict[feature]= feature.feature_value.all()
    
    return render(request, 'products_app/partials/features_filter.html', {'feature_dict':feature_dict})

# ========================  =========================================================================================
class ProductAllView(View):   
    def get(self, request):
        product_all= Product.objects.filter(Q(is_active=True))\
                        .annotate(count= Count('product_name'))\
                        .order_by('-count')
        return render(request, "products_app/shop.html/", {'product_all':product_all})

# ======================== نمایش کالاهای اضافه شده به لیست مقایسه =============================================================================================
class ShowCompareListView(View):
    def get(self,request,*args,**kwargs):
        compare_list = CompareProduct(request)
        context={
            "compare_list" : compare_list,
            }
        return render(request, "products_app/compare_list.html", context)

# #======================= نمایش جدول کالاهای لیست مقایسه ==============================================
def compare_table(request):
    compareList= CompareProduct(request)
    
    
    products=[]
    for productId in compareList.compare_product:
        product=Product.objects.get(id=productId)
        products.append(product) 

    features=[]
    for product in products:
        for item in product.product_features.all():
            if item.feature not in features:
                features.append(item.feature)

    print(100*'*')
    print('products : ', products)
    print('features : ', features)

    print(100*'*')

    context= {
        'products' : products,
        'features' : features
    }
    return render(request, "products_app/partials/compare_table.html", context)

# #======================= محاسبه تعداد کالاهای موجود در لیست مقایسه ==============================================
def status_of_compare_list(request):
    compareList= CompareProduct(request)
    print(100*'*')
    print(compareList.count)
    print(100*'*')
    return HttpResponse(compareList.count)

# #======================= اضافه ردن  کالا به لیست مقایسه ==============================================
def add_to_compare_list(request):
    productId=request.GET.get('productId')
    # productGroupId=request.GET.get('productGroupId')
    compareList=CompareProduct(request)

shop_alma/templates/products_app/compare_list.html
{% extends "main_template.html" %}
{% load render_partial %}
{% block title %}
    لیست مقایسه ها
{% endblock title %}


{% block content %}

    <div id="compare_list">
        {% render_partial "products:compare_table" %}
    </div>

{% endblock content %}

shop_alma/templates/products_app/product_detail copy.html
{% extends "main_template.html" %}
{% load render_partial %}
{% load humanize %}
{% block title %}
جزئیات محصول
{% endblock title %}

{% block content %}     

  <div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h3>{{product.product_name}}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="single-product section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="left-image">
            <img src="{{media_url}}{{product.image_name}}" class="card-img-top align-items-center" alt="...">
                    
                    {% for img in product.gallery_images.all %}
                        <a href="images/products/product-16-1.jpg" target="_blank">
                        <img class="" style="height: 5rem; width: 5rem;" src="{{media_url}}{{img.image_name}}" alt=""> </a>
                    {% endfor %}
          </div>
        </div>
        <div class="col-lg-6 align-self-center">
          <h4>برند: <a href=""> {{product.brand}} </a></h4>
          <span class="price"> قیمت : {{product.price|intcomma}} تومان </span>
          <p class="card-text">{{product.summery_description}}</p>
          <form id="qty" action="#">
            <input type="qty" class="form-control" id="1" aria-describedby="quantity" placeholder="1">
            <button type="submit" onclick="aad_to_shop_cart({{product.id}},1)"><i class="fa fa-shopping-bag"></i><span class="a-icon"> افزودن به سبد خرید </span></button>
          </form>
          <ul>
            
			{% for feature in product.product_features.all %}
                        <label>
                            <input type="radio" name="material">
                                <span>{{feature.feature}}:{{feature.value}}</span>
                        </label>
                        {% endfor %}
            {% comment %} <li><span>Genre:</span> <a href="#">Action</a>, <a href="#">Team</a>, <a href="#">Single</a></li>
            <li><span>Multi-tags:</span> <a href="#">War</a>, <a href="#">Battle</a>, <a href="#">Royal</a></li> {% endcomment %}
          </ul>
                        <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                  <p>{% autoescape off %}
                    {{product.description}}
                    {% endautoescape %}</p>
              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-12">
          <div class="sep"></div>
        </div>
      </div>
    </div>
  </div>





					

							

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

</style>
</head>
<body>

<h2> توضیحات کامل محصولات </h2>

<div class="tab body_C">
  <button class="tablinks" onclick="openCity(event, 'Product')" > درباره محصول </button>
  <button class="tablinks" onclick="openCity(event, 'Comment')"id="defaultOpen"> نظرات </button>
 
</div>

<div id="Product" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>
<div class="product-tabs">
	<div class="product_tabs_c">
		<div class="product-tabs__pane product-tabs__pane--active" id="tab-description">
			<div class="typography">
				<h3>توضیحات کامل محصولات</h3>
				{% autoescape off %}
				{{product.description}}
				{% endautoescape %}

			</div>
		</div>
	</div>
</div>

</div>
<div id="Comment" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>
<div class="view_c" id="btn_{{comment.id}}">
	<div class="reviews-view__list">
		<h3 class="reviews-view__header">دیدگاه های مشتریان</h3>
		<div class="reviews-list">
			<ol class="reviews-list__content">
				{% for comment in product.comments_product.all %}
				{% if comment.is_active %}
				{% if comment.comment_parent == None %}
				<li class="reviews-list__item" style="display: flex; justify-content: space-between;">
					<div class="review">
						<div class="review__vatar">
							<img class="review__avatar" src="{{media_url}}images/avatars/avatar-2.jpg" alt=""></div>
						<div class="review__content">
							<div class="review__author">{{comment.commenting_user.name}}</div>
							<div class="review__text">
								{{comment.comment_text}}
							</div>
							<div class="review__date">{{comment.register_date}}</div>
						</div>
					</div>
					<div>
						{% if user.is_authenticated %}

						<div>
							<a class="btn btn-info" id="btn_{{comment.id}}"
								onclick="showCreateCommentForm({{product.id}},{{comment.id}},'{{product.slug}}');">
								پاسخ
							</a>
						</div>
						<div id="comment_form_{{comment.id}}">

							{% comment %} یه فضای خالی برای فرم {% endcomment %}
						</div>
						{% endif %}
					</div>
				</li>

				{% for item in comment.comments_child.all %}
				{% if comment.is_active %}
				<li class="review-list__item" style="background-color: beige; width:95% margin:10px">
					<div class="review">
						<div class="review__avatar"><img src="{{media_url}}images/avatars/avatar-4.jpg" alt=""></div>
						<div class="review__content">
							<div class="review__author">{{item.commenting_user.name}}</div>
							<div class="review__text">
								{{item.comment_text}}
							</div>
							<div class="review__date">{{item.register_date}}</div>
						</div>
					</div>
				</li>
				{% endif %}
				{% endfor %}
				{% else %}

				{% endif %}
				{% endif %}
				{% endfor %}
			</ol>

			{% if user.is_authenticated %}
			<h3 class="reviews-view__header">دیدگاه های خود را بنویسید</h3>

			<div class="col-12 col-lg-10 ">
				{% render_partial 'csf:create_comment' slug=product.slug %}
			</div>

			{% else %}
			<h5>برای درج دیدگاه خود باید
				<a href="{% url 'accounts:login' %}?next=products/product_details/{{product.slug}}/">ورود</a>
				با
				<a href="{% url 'accounts:register' %}?next=products/product_details/{{product.slug}}/">ثبت نام</a>
				کنید
			</h5>
			{% endif %}
		</div>
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
{% render_partial 'products:related_product' slug=product.slug %}
{% endblock content %}

shop_alma/templates/products_app/product_detail.html
{% extends "main_template.html" %}
{% load render_partial %}
{% load humanize %}
{% block title %}
جزئیات محصول
{% endblock title %}

{% block content %}

<div class="page-heading header-text">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h3>{{product.product_name}}</h3>
			</div>
		</div>
	</div>
</div>

<div class="container-info">
	<div class="contain">

		<div class="right-info main-text">
			<div class="pic-info">
				<img src="{{media_url}}{{product.image_name}}" class="" alt="...">

				{% for img in product.gallery_images.all %}
				<a href="images/products/product-16-1.jpg" target="_blank">
					<img class="" style="height: 5rem; width: 5rem;" src="{{media_url}}{{img.image_name}}" alt=""> </a>
				{% endfor %}
			</div>
			<div class="info-title">
				<h2 class="main-color">ویژگی های محصول</h2>
				<p>{% autoescape off %}
					{{product.description}}
					{% endautoescape %}</p>
			</div>

		</div>

		<div class="left-info main-text">
			<h3>برند: <a href=""> {{product.brand}} </a></h3>
			<p>cho025 : کد کالا</p>

			<ul>

				{% for feature in product.product_features.all %}
				<label>
					<input type="radio" name="material">
					<span>{{feature.feature}}:{{feature.value}}</span>
				</label>
				<br>
				{% endfor %}

			</ul>
			<span class="price"> قیمت : {{product.price|intcomma}} تومان </span>
			<div class="info-icon">
				<i class="fa fa-truck fa-icon"></i>
				<p>تحویل یک روزه</p>
			</div>

			<div class="info-icon">
				<i class="fa fa-money fa-icon"></i>
				<p>با خرید دو عدد فلش بن تخفیف 50.000 تومانی هدیه بگیرید</p>
			</div>
			<div class="info_com">
				<ul class="info_ul">
					<li style="list-style: none;">برند : <a href=""><span
								style="color : red;">{{product.brand}}</span></a>
					</li>
					<li style="list-style: none; ">تعداد نظرات : <a href=""><span
								style="color : red;">{{product.comments_product.all|length}}</span></a> نظر</li>

				</ul>

				<div class="" style="display: flex; justify-content : space-between">

					<h6>میانگین امتیاز کالا : <span style="color : red;">{{product.get_average_score}}</span></h6>

					{% if product.get_user_score > 0 %}
					<div>
						{% with ''|center:5 as range %}
						{% for i in range %}
						{% if forloop.counter <= product.get_user_score %}
						<span id="star_{{ forloop.counter }}" class="fa fa-star checked"></span>
						{% else %}
						<span id="star_{{ forloop.counter }}" class="fa fa-star"></span>
						{% endif %}
						{% endfor %}
						{% endwith %}
					</div>
					{% else %}
					<div>
						<span id="star_1" class="fa fa-star cursor-pointer"
							onclick="addScore(1, {{product.id}})"></span>
						<span id="star_2" class="fa fa-star cursor-pointer"
							onclick="addScore(2, {{product.id}})"></span>
						<span id="star_3" class="fa fa-star cursor-pointer"
							onclick="addScore(3, {{product.id}})"></span>
						<span id="star_4" class="fa fa-star cursor-pointer"
							onclick="addScore(4, {{product.id}})"></span>
						<span id="star_5" class="fa fa-star cursor-pointer"
							onclick="addScore(5, {{product.id}})"></span>
					</div>
					{% endif %}
				</div>
				<div class='compare'>
					<span> اضافه کردن کالا برای مقایسه </span>
					<div>
						<button onclick="addToCompareList({{product.id}},{{product.getMainProductGroup}})" style="cursor:pointer;">
							<div style="margin : 10px; padding: 5px; border: 2px solid #f1f1f1; width: 45px; height: 45; border-radius">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
									stroke-width="1.5" stroke="currentColor" class="size-6">
									<path stroke-linecap="round" stroke-linejoin="round"
										d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
								</svg>
							</div>
						</button>
					</div>
				</div>
			</div>

			<form id="qty" action="#">
				<div class="buy_button">
					<div>
						<button class="btn-small info-btn" type="submit" onclick="add_to_shop_cart({{product.id}},1)">
							<i class="fa fa-shopping-bag"></i>
							<span> افزودن به سبد خرید</span></button>
					</div>
					<div>
						<input type="qty" class="form-quantity" id="1" aria-describedby="quantity" placeholder="1">
					</div>
				</div>
			</form>

		</div>

	</div>

</div>

{% render_partial 'products:related_product' slug=product.slug %}

<!--comments-->
<div class="container-comment">

	<div class="tab body_C">
		<button class="tablinks" onclick="openCity(event, 'Product')"> درباره محصول </button>
		<button class="tablinks" onclick="openCity(event, 'Comment')" id="defaultOpen"> نظرات </button>
	</div>

	<div id="Product" class="tabcontent">
		<span onclick="this.parentElement.style.display='none'" class="topright">&times</span>
		<div class="product-tabs">
			<div class="product_tabs_c">
				<div class="product-tabs__pane product-tabs__pane--active" id="tab-description">
					<div class="typography">
						<h3>توضیحات کامل محصولات</h3>
						{% autoescape off %}
						{{product.description}}
						{% endautoescape %}

					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="Comment" class="tabcontent">
		<span onclick="this.parentElement.style.display='none'" class="topright">&times</span>
		<div class="container">
			<div class="product-tabs">
				<div class="product-tabs__list">
					<a href="#review-form" class="product-tabs__item product-tabs__item--active">دیدگاه ها</a>
				</div>
				<div class="product-tabs__content">
					{% comment %} <div class="product-tabs__pane" id="tab-reviews"> {% endcomment %}
						<div class="reviews-view" id="btn_{{comment.id}}">
							<div class="reviews-view__list">

								<h3 class="reviews-view__header">دیدگاه های مشتریان</h3>
								<div class="reviews-list">
									<ol class="reviews-list__content">
										{% for comment in product.comments_product.all %}
										{% if comment.is_active %}
										{% if comment.comment_parent == None %}
										<li class="reviews-list__item"
											style="display: flex; justify-content: space-between;">
											<div class="review">
												<div class="review__vatar">
													<img class="review__avatar"
														src="{{media_url}}images/avatars/avatar-2.jpg" alt=""></div>
												<div class="review__content">
													<div class="review__author">{{comment.commenting_user.name}}</div>
													<div class="review__text">
														{{comment.comment_text}}
													</div>
													<div class="review__date">{{comment.register_date}}</div>
												</div>
											</div>
											<div>
												{% if user.is_authenticated %}

												<div>
													<a class="btn btn-info" id="btn_{{comment.id}}"
														onclick="showCreateCommentForm({{product.id}},{{comment.id}},'{{product.slug}}');">
														پاسخ
													</a>
												</div>
												<div id="comment_form_{{comment.id}}">

													{% comment %} یه فضای خالی برای فرم {% endcomment %}
												</div>
												{% endif %}
											</div>
										</li>

										{% for item in comment.comments_child.all %}
										{% if comment.is_active %}
										<li class="review-list__item"
											style="background-color: beige; width:95% margin:10px">
											<div class="review">
												<div class="review__avatar"><img
														src="{{media_url}}images/avatars/avatar-4.jpg" alt=""></div>
												<div class="review__content">
													<div class="review__author">{{item.commenting_user.name}}</div>
													<div class="review__text">
														{{item.comment_text}}
													</div>
													<div class="review__date">{{item.register_date}}</div>
												</div>
											</div>
										</li>
										{% endif %}
										{% endfor %}
										{% else %}

										{% endif %}
										{% endif %}
										{% endfor %}
									</ol>

									{% if user.is_authenticated %}
									<h3 class="reviews-view__header">دیدگاه های خود را بنویسید</h3>
									<div class="row">
										<div class="col-12 col-lg-9 col-xl-8">
											{% render_partial 'csf:create_comment' slug=product.slug %}
										</div>
									</div>

									{% else %}
									<h5>برای درج دیدگاه خود باید
										<a
											href="{% url 'accounts:login' %}?next=products/product_details/{{product.slug}}/">ورود</a>
										با
										<a
											href="{% url 'accounts:register' %}?next=products/product_details/{{product.slug}}/">ثبت
											نام</a>
										کنید
									</h5>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!--comments-->
	</div>
	{% endblock content %}

shop_alma/templates/products_app/product_groups.html
{% extends "main_template.html" %}
{% load render_partial %}
{% load humanize %}
{% block title %}
    صفحه اول
{% endblock title %}

{% block content %}
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">دسته های محبوب</h3>
            <div class="block-header__divider"></div>
        </div>
        <div class="block-categories__list-all">
            {% for group in product_groups %}
            <div class="block-categories__item category-card category-card--layout--compact">
                <div class="category-card__body">
                    <div class="category-card__image">
                        <a href="">
                            <img src="{{media_url}}{{group.image_name}}" alt="">
                        </a>
                    </div>
                    <div class="category-card__content">
                        <div class="category-card__name"><a href="">{{group.group_title}}</a></div>
                        <div class="category-card__products">{{group.product_of_groups.all|length}} محصول</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <a href='{% url "products:product_groups" %}'>همه</a>
        </div>
    </div>
</div>
{% endblock content %}