shop_alma/apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name= 'register'),
    path('verify/', views.VerifyRegisterCodeView.as_view(), name= 'verify'),
    path('login/', views.LoginUserView.as_view(), name= 'login'),
    path('logout/', views.LogoutUserView.as_view(), name= 'logout'),
    path('remember_password/', views.RememberPasswordView.as_view(), name= 'remember_password'),
    path('change_password/', views.ChengPasswordView.as_view(), name= 'change_password'),
    
    path('userpanel/', views.UserPanelView.as_view(), name= 'userpanel'),
    path('show_last_orders/',views.show_last_orders,name='show_last_orders'),
    path('update_profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('show_user_payment/',views.show_user_payments,name='show_user_payment'),
    
]

shop_alma/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls", namespace= "main")),
    path('accounts/', include("apps.accounts.urls", namespace= "accounts")),
    path('products/', include("apps.products.urls", namespace= "products")),
    path('orders/', include("apps.orders.urls", namespace= "orders")),
    path('discounts/', include('apps.discounts.urls', namespace= "discounts")),
    path('payments/',include('apps.payment.urls',namespace='payments')),
    path('warehouses/', include("apps.warehouses.urls", namespace= "warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace='csf')),
    path("search/",include("apps.search.urls",namespace='search')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='apps.main.views.handler404'

shop_alma/templates/main_template.html
<html lang="en">
<head>
    <meta charset="utf-8">   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load humanize %}
    <title>
        {% block title %}{% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
	<link rel="stylesheet" href='{% static "/vendor/bootstrap/css/bootstrap.min.css" %}'>
    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href='{% static "/assets/css/fontawesome.css" %}'>
	  <link rel="stylesheet" href='{% static "/assets/css/templatemo-lugx-gaming.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/owl.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/animate.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/my_style.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/login.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/util.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/style.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/owl.theme.css" %}'>
    <link rel="stylesheet" href='{% static "/assets/css/owl.carousel.min.css" %}'>

    
    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src='{% static "/vendor/jquery/jquery.min.js" %}'></script>
    <script src='{% static "/vendor/bootstrap/js/bootstrap.min.js" %}'></script>
    <script src='{% static "/assets/js/isotope.min.js" %}'></script>
    <script src='{% static "/assets/js/owl-carousel.js" %}'></script>
    <script src='{% static "/assets/js/counter.js" %}'></script>
    <script src='{% static "/assets/js/custom.js" %}'></script>
    <script src='{% static "/assets/js/myscript.js" %}'></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src='{% static "/assets/js/owl.carousel.js" %}'></script>



  <!--
  TemplateMo 589 lugx gaming
  https://templatemo.com/tm-589-lugx-gaming
  -->
</head>

<body dir="rtl">

  <!-- ***** Preloader End ***** -->
    {% include "partials/header.html" %}

    {% block content %}

    {% endblock content %}

    {% include "partials/footer.html" %}


</body>
</html>

shop_alma/templates/user_panel_template.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>
		{% block title %}{% endblock %}
	</title>

	{% comment %}
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
		rel="stylesheet"> {% endcomment %}

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href='{% static "/vendor/bootstrap/css/bootstrap.min.css" %}'>

	<!-- Additional CSS Files -->
	<link rel="stylesheet" href='{% static "/assets/css/fontawesome.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/templatemo-lugx-gaming.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/owl.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/animate.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/my_style.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/login.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/util.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/style.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/owl.theme.css" %}'>
	<link rel="stylesheet" href='{% static "/assets/css/owl.carousel.min.css" %}'>

	<!-- Scripts -->
	<!-- Bootstrap core JavaScript -->
	<script src='{% static "/vendor/jquery/jquery.min.js" %}'></script>
	<script src='{% static "/vendor/bootstrap/js/bootstrap.min.js" %}'></script>
	<script src='{% static "/assets/js/isotope.min.js" %}'></script>
	<script src='{% static "/assets/js/owl-carousel.js" %}'></script>
	<script src='{% static "/assets/js/counter.js" %}'></script>
	<script src='{% static "/assets/js/custom.js" %}'></script>
	<script src='{% static "/assets/js/myscript.js" %}'></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src='{% static "/assets/js/owl.carousel.js" %}'></script>

	<!--
  TemplateMo 589 lugx gaming
  https://templatemo.com/tm-589-lugx-gaming
  -->
</head>

<body>

	{% comment %} {% include "partials/user_panel_header.html" %} {% endcomment %}

	<!-- site__body -->
	<div>
		{% include "partials/navbar.html" %}
		<div>
			{% include "partials/banner/banner_box.html" with type=4 %}
		</div> 

		<div class="block">
			<div class="container">
				<div class="row">
					<div class="d-flex">
					<div class="col-12 col-lg-3 ">
						<div class="account-nav" style="border: 1px solid red;">
							<h4 class="account-nav__title">ناوبری</h4>
							<ul>
								<li class="account-nav__item account-nav__item--active"><a
										href="{% url 'accounts:userpanel' %}">داشبورد</a></li>
								<li class="account-nav__item"><a href="{% url 'accounts:update_profile' %}">ویرایش
										پروفایل</a></li>
								<li class="account-nav__item"><a href="{% url 'accounts:show_user_payment' %}">سابقه
										خرید</a></li>
								<li class="account-nav__item"><a href="{% url 'accounts:change_password' %}">تغییر رمز
										عبور</a></li>
								<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
							</ul>
						</div>
					</div>
					<div class="col-12 col-lg-9 mt-4 mt-lg-0">
						{% block content %}
						
						{% endblock content %}
					</div>
					</div>
				</div>
			</div>
		</div>

		<!-- site__body / end -->
	</div>

	{% include "partials/footer.html" %}

</body>

</html>